version: '2'
services:
  mysqlmaster:
    image: mysql:5.6
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ./data/mysql-master:/var/lib/mysql/
      - ./config/mysql-master:/etc/mysql/conf.d/
  mysqlslave:
    image: mysql:5.6
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ./data/mysql-slave:/var/lib/mysql/
      - ./config/mysql-slave:/etc/mysql/conf.d/
  mysqlconfigure:
    image: mysql:5.6
    environment:
      - "MYSQL_SLAVE_PASSWORD=root"
      - "MYSQL_MASTER_USER=quantimodo"
      - "MYSQL_MASTER_PASSWORD="
      - "MYSQL_MASTER_HOST="
      - "MYSQL_REPLICATION_USER=replication"
      - "MYSQL_REPLICATION_PASSWORD="
    volumes:
      - ./mysql_connector.sh:/tmp/mysql_connector.sh
    command: /bin/bash -x /tmp/mysql_connector.sh
